const processed = new Set();

chrome.webRequest.onCompleted.addListener((details) => {
    // Only target the primary document structure JSON request
    if (details.url.includes("sub_id=txt_all.json")) {
        // Skip bypass requests generated by our own content script
        if (details.url.includes("_ext=1")) {
            return;
        }
        
        // Ensure we don't trigger multiple times for the same tab in quick succession
        const key = details.tabId + '_' + details.url;
        if (processed.has(key)) return;
        
        processed.add(key);
        setTimeout(() => processed.delete(key), 10000); // Clear after 10 seconds

        // Notify content script on the page where the request generated
        chrome.tabs.sendMessage(details.tabId, {
            type: 'PROCESS_DOCUMENT',
            url: details.url
        }).catch(err => {
            console.log('Feishu Doc Downloader: Could not send message to tab', err);
        });
    }
}, { urls: ["*://*.feishu.cn/space/api/box/stream/download/preview_sub/*"] });
